lib: [
  "/Users/wczekalski/Documents/Work/Projects.nosync/covid19chart/_esy/default/store/b/covid19chart-93beea46/install/default/lib/data-processor/META"
  "/Users/wczekalski/Documents/Work/Projects.nosync/covid19chart/_esy/default/store/b/covid19chart-93beea46/install/default/lib/data-processor/dune-package"
  "/Users/wczekalski/Documents/Work/Projects.nosync/covid19chart/_esy/default/store/b/covid19chart-93beea46/install/default/lib/data-processor/opam"
]
bin: [
  "/Users/wczekalski/Documents/Work/Projects.nosync/covid19chart/_esy/default/store/b/covid19chart-93beea46/install/default/bin/data-processor.exe"
]
doc: [
  "/Users/wczekalski/Documents/Work/Projects.nosync/covid19chart/_esy/default/store/b/covid19chart-93beea46/install/default/doc/data-processor/README.md"
]
