name: GitHub pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - name: Install esy
      run: npm install -g esy@0.6.2
    - name: Install dependencies
      run: esy install
    - name: Print esy cache
      id: print_esy_cache
      run: node .github/workflows/print_esy_cache.js
    - name: Try to restore dependencies cache
      id: deps-cache-macos
      uses: actions/cache@v1
      with:
        path: ${{ steps.print_esy_cache.outputs.esy_cache }}
        key: ${{ matrix.os }}-${{ hashFiles('**/index.json') }}
    - name: Build dependencies
      run: esy build
    - name: Run data processor
      run: ./data_update.sh
    - name: Install node dependencies
      run: yarn
    - name: Build
      run: yarn prod
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./bundleOutput
